name: Project SR Calculation

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Runs Project
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
        working-directory: projects/sr-calc/
        run: |
          chmod +x ./run.sh
          ./run.sh mytest << EOF
          1
          EOF

      - name: Checks Project Files
        run: |
          ls osu.view/sr-calc/mytest/
