name: Project SR Calculation

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Runs Project
        working-directory: projects/sr-calc/
        run: |
          chmod +x ./run.sh
          ./run.sh mytest << EOF
          1
          EOF

      - name: Assert Essential Project Files exist
        run: |
          if [ ! -f osu.view/sr-calc/mytest/nt.results.json ]; then
            echo Missing expected nt.results.json 
            exit 1
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: SR Calculation Results
          path: osu.view/sr-calc/mytest/
