name: Project SR Calculation

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Runs Project
        working-directory: ./project/sr-calc/
        run: |
          ./run.sh mytest << EOF
          1
          EOF

      - name: Checks Project Files
        run: |
          ls osu.view/sr-calc/mytest/
