name: Project SR Calculation

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Runs Project
        working-directory: projects/sr-calc/
        run: |
          ./run.sh mytest << EOF
          1
          EOF

      - name: Checks Project Files
        run: |
          ls osu.view/sr-calc/mytest/
