name: SR Calculation with Service Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Start Service in osu-tools-docker
        working-directory: osu-tools-docker/
        run: |
          docker-compose up --wait || exit 1

      - name: Start Service in osu-data-docker
        working-directory: osu-data-docker/
        run: |
          docker-compose --env-file test/.test.env up --wait || exit 1

      - name: Runs initial, new test
        working-directory: projects/sr-calc/
        run: |
          chmod +x ./run.sh
          ./run.sh -r mytest \
                   -y https://github.com/Eve-ning/osu-data-docker/raw/master/rsc/YYYY_MM_DD_performance_mania_top_1000.tar.bz2 \
                   -z https://github.com/Eve-ning/osu-data-docker/raw/master/rsc/YYYY_MM_DD_osu_files.tar.bz2 \
                   -q "SELECT beatmap_id FROM osu_beatmaps WHERE playmode = 3 AND approved = 1 LIMIT 10" \
          << EOF
          1
          EOF || exit 1

      - name: Assert that only results, files, query exist
        run: |
          [ -f osu.view/sr-calc/mytest/nt.results.json ] || exit 1 
          [ -d osu.view/sr-calc/mytest/files ] || exit 2
          [ -f osu.view/sr-calc/mytest/query.sql ] || exit 3 
          [ ! -f osu.view/sr-calc/mytest/.env ] || exit 4

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: SR Calculation with Service Results
          path: osu.view/sr-calc/
